version: "3.3"
services:
  httpd:
    container_name: $CONTAINER_NAME
    image: nginx
    restart: always
    expose:
      - 80
      - 443
    environment:
      - VIRTUAL_HOST=${VIRTUAL_HOST:?set it in .env}
      - LETSENCRYPT_HOST=${VIRTUAL_HOST:?set it in .env}
      - LETSENCRYPT_EMAIL=frederick@podmytube.com
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - $DATA_DIR:/usr/share/nginx/html
    networks:
      - nginx-proxy

networks:
  nginx-proxy:
    external: true
