version: '3.3'
services:  
  # ==============================================================
  # here we are building image from the .docker/Dockerfile
  # this image is starting from a official php-apache docker
  # and creating host dashboard-pmt
  httpd:
    container_name: ${CONTAINER_NAME:?set it in .env}
    build:
      context: .
      dockerfile: .docker/Dockerfile
    image: static.pmt
    restart: always
    expose:
        - 80
        - 443
    # VIRTUAL_HOST should be only the domain (without http://)
    # by example : www.example.com or sub.domain.fr
    environment:
      - VIRTUAL_HOST=${VIRTUAL_HOST:?set it in .env}
      - LETSENCRYPT_HOST=${VIRTUAL_HOST:?set it in .env}
      - LETSENCRYPT_EMAIL=frederick@tyteca.net
    volumes:
      - ./data/:/var/www/html/
    networks:
      - nginx-proxy
    

networks:
  nginx-proxy:
    external: true
